# Generated by Django 4.2.7 on 2026-02-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_qr_codes/'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(choices=[('PHONEPE', 'Phone Pe'), ('GPAY', 'Google Pay'), ('PAYTM', 'Paytm'), ('UPI', 'UPI'), ('BANK', 'Bank Account'), ('QR', 'QR')], max_length=20),
        ),
    ]
