# Generated by Django 4.2.7 on 2026-02-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_paymentmethod_qr_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('otp_code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('LOGIN', 'Login'), ('REGISTRATION', 'Registration'), ('PASSWORD_RESET', 'Password Reset')], default='LOGIN', max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', '-created_at'], name='accounts_ot_phone_n_5c3b8d_idx'), models.Index(fields=['expires_at'], name='accounts_ot_expires_57ad4f_idx')],
            },
        ),
    ]
