# Generated by Django 4.2.7 on 2026-02-08 17:41

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('reward_type', models.CharField(choices=[('MONEY', 'Money Reward'), ('TRY_AGAIN', 'Try Again')], default='MONEY', max_length=20)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('reward_date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-claimed_at'],
                'unique_together': {('user', 'reward_date')},
            },
        ),
    ]
