# Generated by Django 4.2.7 on 2026-02-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_dailyreward'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='verification_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('REGISTRATION', 'Registration'), ('PASSWORD_RESET', 'Password Reset'), ('SIGNUP', 'Signup')], default='LOGIN', max_length=20),
        ),
    ]
