# Generated by Django 4.2.7 on 2026-02-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_add_verification_id_to_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
