# Generated by Django 4.2.7 on 2026-02-10 16:17

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_user_referral_code_user_referred_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositrequest',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_requests', to='accounts.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(choices=[('PHONEPE', 'Phone Pe'), ('GPAY', 'Google Pay'), ('PAYTM', 'Paytm'), ('UPI', 'UPI'), ('BANK', 'Bank Account'), ('QR', 'QR'), ('USDT_TRC20', 'USDT (TRC20)'), ('USDT_BEP20', 'USDT (BEP20)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw'), ('BET', 'Bet'), ('WIN', 'Win'), ('REFUND', 'Refund'), ('REFERRAL_BONUS', 'Referral Bonus'), ('MILESTONE_BONUS', 'Milestone Bonus')], max_length=20),
        ),
        migrations.CreateModel(
            name='LuckyDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('deposit_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lucky_draws', to='accounts.depositrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lucky_draws', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-claimed_at'],
            },
        ),
    ]
