# Generated by Django 4.2.7 on 2026-02-10 19:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_remove_bonus_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='unavaliable_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount currently locked or unavaliable for withdrawal', max_digits=10),
        ),
    ]
