# Generated by Django 4.2.7 on 2026-02-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_wallet_unavaliable_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='usdt_network',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='usdt_wallet_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
