# Generated by Django 4.2.7 on 2026-02-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_paymentmethod_usdt_network_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='usdt_network',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='usdt_wallet_address',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
