# Generated by Django 4.2.7 on 2026-02-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_add_usdt_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(choices=[('PHONEPE', 'Phone Pe'), ('GPAY', 'Google Pay'), ('PAYTM', 'Paytm'), ('UPI', 'UPI'), ('BANK', 'Bank Account'), ('QR', 'QR'), ('USDT_TRC20', 'USDT (TRC20)'), ('USDT_BEP20', 'USDT (BEP20)')], max_length=20),
        ),
    ]
