# Generated by Django 4.2.7 on 2026-02-11 14:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_remove_generic_usdt'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='usdt_exchange_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('90.00'), help_text='1 USDT = X Rupees', max_digits=10),
        ),
    ]
