# Generated by Django 4.2.7 on 2026-02-22 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_wallet_turnover'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawrequest',
            name='utr_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dailyreward',
            name='reward_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='depositrequest',
            name='amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='luckydraw',
            name='deposit_amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='luckydraw',
            name='reward_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='usdt_exchange_rate',
            field=models.BigIntegerField(default=90, help_text='1 USDT = X Rupees'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_after',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_before',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='unavaliable_balance',
            field=models.BigIntegerField(default=0, help_text='Amount currently locked or unavaliable for withdrawal'),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('COMPLETED', 'Payment Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.CharField(max_length=500)),
                ('platform', models.CharField(default='android', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='accounts_de_user_id_92951d_idx'), models.Index(fields=['fcm_token'], name='accounts_de_fcm_tok_6fd4a4_idx')],
                'unique_together': {('user', 'fcm_token')},
            },
        ),
    ]
