# Generated by Django 4.2.7 on 2026-03-13 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_wallet_total_deposits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw'), ('BET', 'Bet'), ('WIN', 'Win'), ('REFUND', 'Refund'), ('REFERRAL_BONUS', 'Referral Bonus'), ('MILESTONE_BONUS', 'Milestone Bonus'), ('LEADERBOARD_PRIZE', 'Leaderboard Prize')], max_length=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='turnover',
            field=models.BigIntegerField(default=0, help_text='Total amount wagered. Unavailable = max(0, total_deposits - turnover).'),
        ),
        migrations.CreateModel(
            name='FranchiseBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.BigIntegerField(default=0, help_text='Balance in same unit as Wallet (e.g. rupees)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='franchise_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Franchise balance',
                'verbose_name_plural': 'Franchise balances',
            },
        ),
        migrations.AddConstraint(
            model_name='franchisebalance',
            constraint=models.CheckConstraint(check=models.Q(('balance__gte', 0)), name='franchise_balance_non_negative'),
        ),
    ]
