# Generated by Django 4.2.7 on 2026-03-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_franchise_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchisebalance',
            name='franchise_name',
            field=models.CharField(blank=True, help_text='Franchise / owner display name (e.g. Muktesh)', max_length=120),
        ),
    ]
