# Generated by Django 4.2.7 on 2026-03-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_franchise_balance_add_franchise_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_franchise_only',
            field=models.BooleanField(default=False),
        ),
    ]
