# Generated by Django 4.2.7 on 2026-03-13 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_user_is_franchise_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseBalanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ADD', 'Add'), ('SET', 'Set')], max_length=10)),
                ('amount', models.BigIntegerField(help_text='For Add: amount added. For Set: new balance value.')),
                ('balance_after', models.BigIntegerField(blank=True, help_text='Balance after this action', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='franchise_balance_actions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Franchise admin who received the balance', on_delete=django.db.models.deletion.CASCADE, related_name='franchise_balance_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Franchise balance log',
                'verbose_name_plural': 'Franchise balance logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
