# Generated by Django 4.2.7 on 2026-03-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_franchise_balance_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchisebalance',
            name='help_telegram',
            field=models.CharField(blank=True, help_text="Help Center Telegram number/username for this franchise's APK.", max_length=30),
        ),
        migrations.AddField(
            model_name='franchisebalance',
            name='help_whatsapp_number',
            field=models.CharField(blank=True, help_text="Help Center WhatsApp number for this franchise's APK (e.g. +919876543210).", max_length=30),
        ),
        migrations.AddField(
            model_name='franchisebalance',
            name='package_name',
            field=models.CharField(blank=True, help_text="APK package name for this franchise; Help Center API returns this franchise's numbers when app sends this package.", max_length=255, null=True, unique=True),
        ),
    ]
