# Generated by Django 4.2.7 on 2026-03-14 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_franchise_help_center_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='works_under',
            field=models.ForeignKey(blank=True, help_text="For workers: the admin under whom this worker is assigned. This worker will see that admin's deposit/withdraw requests.", limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_workers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='worker',
            field=models.ForeignKey(blank=True, help_text='For players: the franchise admin (or Super Admin) this user is under. Deposit/withdraw requests show to that admin.', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to=settings.AUTH_USER_MODEL),
        ),
    ]
