# Generated by Django 4.2.7 on 2026-04-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_wallet_deposit_rotation_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchisebalance',
            name='help_facebook',
            field=models.CharField(blank=True, help_text="Help Center Facebook page or profile URL for this franchise's APK.", max_length=500),
        ),
        migrations.AddField(
            model_name='franchisebalance',
            name='help_instagram',
            field=models.CharField(blank=True, help_text="Help Center Instagram profile URL or handle for this franchise's APK.", max_length=500),
        ),
        migrations.AddField(
            model_name='franchisebalance',
            name='help_youtube',
            field=models.CharField(blank=True, help_text="Help Center YouTube channel URL for this franchise's APK.", max_length=500),
        ),
    ]
