# Generated by Django 4.2.7 on 2026-04-29 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_franchise_help_social_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw'), ('BET', 'Bet'), ('WIN', 'Win'), ('REFUND', 'Refund'), ('REFERRAL_BONUS', 'Referral Bonus'), ('REFERRAL_COMMISSION', 'Referral Commission'), ('MILESTONE_BONUS', 'Milestone Bonus'), ('LEADERBOARD_PRIZE', 'Leaderboard Prize')], max_length=20),
        ),
        migrations.CreateModel(
            name='ReferralDailyCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_date', models.DateField(db_index=True)),
                ('opening_balance', models.BigIntegerField()),
                ('closing_balance', models.BigIntegerField()),
                ('loss_amount', models.BigIntegerField()),
                ('commission_rate', models.DecimalField(decimal_places=4, max_digits=7)),
                ('commission_amount', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_commission_generated', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_commission_earnings', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_daily_commission_detail', to='accounts.transaction')),
            ],
            options={
                'ordering': ('-commission_date', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='referraldailycommission',
            constraint=models.UniqueConstraint(fields=('referee', 'commission_date'), name='uniq_referral_daily_comm_referee_date'),
        ),
    ]
