# Generated by Django 4.2.7 on 2026-02-06 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_adminpermissions_can_manage_payment_methods'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bet',
            unique_together=set(),
        ),
    ]
