# Generated by Django 4.2.7 on 2026-02-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_whitelabel_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize_1st', models.BigIntegerField(default=1000)),
                ('prize_2nd', models.BigIntegerField(default=500)),
                ('prize_3rd', models.BigIntegerField(default=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
