# Generated by Django 4.2.7 on 2026-02-26 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_leaderboard_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_end', models.DateTimeField(help_text='Leaderboard period end time (UTC).')),
                ('rank', models.IntegerField()),
                ('amount', models.BigIntegerField()),
                ('transaction_id', models.BigIntegerField(blank=True, null=True)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-awarded_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='leaderboardpayout',
            constraint=models.UniqueConstraint(fields=('period_end', 'rank'), name='uniq_leaderboard_payout_period_rank'),
        ),
        migrations.AddConstraint(
            model_name='leaderboardpayout',
            constraint=models.UniqueConstraint(fields=('period_end', 'user'), name='uniq_leaderboard_payout_period_user'),
        ),
    ]
