# Generated by Django 4.2.7 on 2026-02-27 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0016_leaderboard_payout'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRewardProbability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob_low', models.FloatField(default=70.0)),
                ('prob_medium', models.FloatField(default=20.0)),
                ('prob_high', models.FloatField(default=9.0)),
                ('prob_mega', models.FloatField(default=1.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Daily Reward Probabilities',
            },
        ),
        migrations.CreateModel(
            name='MegaSpinProbability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob_1', models.FloatField(default=12.5)),
                ('prob_2', models.FloatField(default=12.5)),
                ('prob_3', models.FloatField(default=12.5)),
                ('prob_4', models.FloatField(default=12.5)),
                ('prob_5', models.FloatField(default=12.5)),
                ('prob_6', models.FloatField(default=12.5)),
                ('prob_7', models.FloatField(default=12.5)),
                ('prob_8', models.FloatField(default=12.5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Mega Spin Probabilities',
            },
        ),
        migrations.CreateModel(
            name='UserSoundSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_music_volume', models.FloatField(default=0.5)),
                ('is_muted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bet',
            name='chip_amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='bet',
            name='payout_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='total_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['created_at', 'user_id'], name='bet_leaderboard_created_user'),
        ),
        migrations.AddField(
            model_name='usersoundsetting',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sound_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='megaspinprobability',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mega_spin_probability', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyrewardprobability',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_reward_probability', to=settings.AUTH_USER_MODEL),
        ),
    ]
