# Generated by Django 4.2.7 on 2026-03-11 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0018_userdailyturnover'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('account_ids_json', models.TextField(default='[]')),
                ('flagged_ids_json', models.TextField(default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IP Tracker',
                'verbose_name_plural': 'IP Trackers',
            },
        ),
        migrations.CreateModel(
            name='PlayerDailyState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('active_day_number', models.PositiveIntegerField(default=1)),
                ('day_type', models.CharField(choices=[('WIN', 'Win Day'), ('LOSS', 'Loss Day'), ('BREAK_EVEN', 'Break Even Day'), ('BIG_WIN', 'Big Win Day')], default='WIN', max_length=20)),
                ('deposit_today', models.BigIntegerField(default=0)),
                ('floor_balance', models.BigIntegerField(default=0)),
                ('emergency_floor', models.BigIntegerField(default=0)),
                ('target_min', models.BigIntegerField(default=0)),
                ('target_max', models.BigIntegerField(default=0)),
                ('daily_budget', models.BigIntegerField(default=0)),
                ('budget_used', models.BigIntegerField(default=0)),
                ('time_target_seconds', models.IntegerField(default=3600)),
                ('time_played_seconds', models.IntegerField(default=0)),
                ('time_target_reached', models.BooleanField(default=False)),
                ('rounds_today', models.IntegerField(default=0)),
                ('rounds_since_last_win', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Player Daily State',
                'verbose_name_plural': 'Player Daily States',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PlayerJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_json', models.TextField(default='[]')),
                ('active_days', models.PositiveIntegerField(default=0)),
                ('last_play_date', models.DateField(blank=True, null=True)),
                ('first_deposit_date', models.DateField(blank=True, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Player Journey',
                'verbose_name_plural': 'Player Journeys',
            },
        ),
        migrations.RemoveConstraint(
            model_name='userdailyturnover',
            name='game_userdailyturnover_user_period_date_uniq',
        ),
        migrations.AlterUniqueTogether(
            name='userdailyturnover',
            unique_together={('user', 'period_date')},
        ),
        migrations.AddField(
            model_name='playerjourney',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journey', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playerdailystate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_states', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='playerdailystate',
            unique_together={('user', 'date')},
        ),
    ]
