# Generated by Django 4.2.7 on 2026-03-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_addiction_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpermissions',
            name='can_view_help_center',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminpermissions',
            name='can_view_white_label',
            field=models.BooleanField(default=False),
        ),
    ]
