# Generated by Django 4.2.7 on 2026-03-14 10:13
# Idempotent: safe to run when column already exists (e.g. added manually or on another DB).

from django.db import migrations, models


def add_can_view_game_history_if_missing(apps, schema_editor):
    """Add column only if it does not exist (avoids error when column already present)."""
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT 1 FROM information_schema.columns
            WHERE table_name = 'game_adminpermissions' AND column_name = 'can_view_game_history'
        """)
        if cursor.fetchone():
            return
    # Column missing: add it
    schema_editor.execute(
        "ALTER TABLE game_adminpermissions ADD COLUMN can_view_game_history BOOLEAN NOT NULL DEFAULT true"
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_add_help_center_white_label_permissions'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='adminpermissions',
                    name='can_view_game_history',
                    field=models.BooleanField(default=True),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_can_view_game_history_if_missing, noop_reverse),
            ],
        ),
    ]
