# Generated by Django 4.2.7 on 2026-04-03 21:25

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0024_colour_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='CockFightSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('SETTLED', 'Settled')], db_index=True, default='OPEN', max_length=20)),
                ('winner', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CockFightBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(max_length=10)),
                ('stake', models.BigIntegerField(help_text='Stake in same unit as wallet balance (e.g. rupees)')),
                ('odds', models.DecimalField(decimal_places=2, default=Decimal('9.00'), max_digits=10)),
                ('potential_payout', models.BigIntegerField(help_text='Total return if win (stake × odds), stake already deducted')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('WON', 'Won'), ('LOST', 'Lost'), ('VOID', 'Void')], default='PENDING', max_length=20)),
                ('payout_amount', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='game.cockfightsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cock_fight_bets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', 'status'], name='cockfightbet_sess_stat_idx')],
            },
        ),
    ]
