# Generated by Django 4.2.7 on 2026-04-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_cockfight_round_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cockfightroundvideo',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='cockfightroundvideo',
            name='session',
        ),
    ]
