# Generated by Django 4.2.7 on 2026-04-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_cockfight_round_video_auto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpermissions',
            name='can_upload_cockfight_videos',
            field=models.BooleanField(default=True),
        ),
    ]
