# Generated by Django 4.2.7 on 2026-04-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_cockfight_round_video_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='cockfightroundvideo',
            name='duration_seconds',
            field=models.FloatField(
                blank=True,
                help_text='Video length in seconds (ffprobe); used to drop stream URL after broadcast ends.',
                null=True,
            ),
        ),
    ]
