# Generated by Django 4.2.7 on 2026-04-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0032_cockfight_round_video_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cockfightbet',
            name='potential_payout',
            field=models.BigIntegerField(help_text='Total return if win'),
        ),
        migrations.AlterField(
            model_name='cockfightbet',
            name='stake',
            field=models.BigIntegerField(help_text='Stake in same unit as wallet balance'),
        ),
        migrations.AlterField(
            model_name='cockfightroundvideo',
            name='scheduled_start',
            field=models.DateTimeField(blank=True, help_text='Wall-clock time when playback should start for everyone (simulated live).', null=True),
        ),
        migrations.AlterField(
            model_name='cricketbet',
            name='stake',
            field=models.BigIntegerField(help_text='Stake in rupees'),
        ),
    ]
