# Generated by Django 4.2.7 on 2026-04-29 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0033_alter_cockfightbet_potential_payout_and_more'),
        ('game', '0033_cockfight_video_quality_variants'),
    ]

    operations = [
    ]
