# Generated by Django 4.2.7 on 2026-04-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0034_merge_20260429_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='cockfightroundvideo',
            name='hls_ready',
            field=models.BooleanField(default=False, help_text='True once HLS segments have been generated for adaptive streaming.'),
        ),
        migrations.AddField(
            model_name='cockfightroundvideo',
            name='hls_token',
            field=models.CharField(blank=True, default='', help_text='Random UUID used as the private HLS directory path.', max_length=64),
        ),
    ]
