# Generated by Django 4.2.7 on 2026-04-29 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0035_cockfight_hls_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cockfightroundvideo',
            name='video_360p',
        ),
        migrations.RemoveField(
            model_name='cockfightroundvideo',
            name='video_720p',
        ),
    ]
