# Generated by Django 4.2.7 on 2026-04-30 14:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0039_cockfight_round_side_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='cockfightroundvideo',
            name='odds_cock1',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.90'), help_text='Decimal odds for COCK1 this round (required on upload; incl. stake).', max_digits=10),
        ),
        migrations.AddField(
            model_name='cockfightroundvideo',
            name='odds_cock2',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.92'), help_text='Decimal odds for COCK2 this round (required on upload; incl. stake).', max_digits=10),
        ),
    ]
